question_data = [
    {
        "category": "Entertainment: Cartoon & Animations", "type": "boolean", "difficulty": "easy",
        "question": "In the &quot;Shrek&quot; film franchise, Donkey is played by Eddie Murphy.",
        "correct_answer": "True",
        "incorrect_answers": ["False"]},
    {"category": "Entertainment: Video Games", "type": "multiple", "difficulty": "easy",
     "question": "League of Legends, DOTA 2, Smite and Heroes of the Storm are all part of which game genre?",
     "correct_answer": "Multiplayer Online Battle Arena (MOBA)",
     "incorrect_answers": ["Real Time Strategy (RTS)", "First Person Shooter (FPS)", "Role Playing Game (RPG)"]},
    {"category": "Entertainment: Video Games", "type": "multiple", "difficulty": "easy",
     "question": "In the Nintendo DS game &#039;Ghost Trick: Phantom Detective&#039;, what is the name of the hitman seen at the start of the game?",
     "correct_answer": "Nearsighted Jeego", "incorrect_answers": ["One Step Ahead Tengo", "Missile", "Cabanela"]},
    {"category": "Animals", "type": "multiple", "difficulty": "easy",
     "question": "What is the fastest  land animal?",
     "correct_answer": "Cheetah", "incorrect_answers": ["Lion", "Thomson&rsquo;s Gazelle", "Pronghorn Antelope"]},
    {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
     "question": "The name of the main character of the video game &quot;The Legend of Zelda&quot;, is Zelda.",
     "correct_answer": "False", "incorrect_answers": ["True"]},
    {"category": "Entertainment: Books", "type": "multiple", "difficulty": "easy",
     "question": "Which famous book is sub-titled &#039;The Modern Prometheus&#039;?",
     "correct_answer": "Frankenstein",
     "incorrect_answers": ["Dracula", "The Strange Case of Dr. Jekyll and Mr. Hyde ",
                           "The Legend of Sleepy Hollow"]},
    {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
     "question": "The song &quot;Megalovania&quot; by Toby Fox made its third appearence in the 2015 RPG &quot;Undertale&quot;.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"category": "Science & Nature", "type": "multiple", "difficulty": "easy",
     "question": "What is the elemental symbol for mercury?", "correct_answer": "Hg",
     "incorrect_answers": ["Me", "Mc", "Hy"]},
    {"category": "Entertainment: Video Games", "type": "multiple", "difficulty": "easy",
     "question": "Which of these is a type of monster found in Minecraft?", "correct_answer": "Skeleton",
     "incorrect_answers": ["Werewolf", "Vampire", "Minotaur"]},
    {"category": "Science & Nature", "type": "multiple", "difficulty": "easy",
     "question": "What is the first element on the periodic table?", "correct_answer": "Hydrogen",
     "incorrect_answers": ["Helium", "Oxygen", "Lithium"]},
    {"category": "Entertainment: Video Games", "type": "multiple", "difficulty": "easy",
     "question": "Half-Life by Valve uses the GoldSrc game engine, which is a highly modified version of what engine?",
     "correct_answer": "Quake Engine", "incorrect_answers": ["Doom Engine", "id Engine", "Source Engine"]},
    {"category": "Mythology", "type": "multiple", "difficulty": "easy",
     "question": "Who in Greek mythology, who led the Argonauts in search of the Golden Fleece?",
     "correct_answer": "Jason", "incorrect_answers": ["Castor", "Daedalus", "Odysseus"]},
    {"category": "Entertainment: Video Games", "type": "multiple", "difficulty": "easy",
     "question": "If a &quot;360 no-scope&quot; is one full rotation before shooting, how many rotations would a &quot;1080 no-scope&quot; be?",
     "correct_answer": "3", "incorrect_answers": ["4", "2", "5"]},
    {"category": "Geography", "type": "multiple", "difficulty": "easy",
     "question": "What is the capital of Denmark?",
     "correct_answer": "Copenhagen", "incorrect_answers": ["Aarhus", "Odense", "Aalborg"]},
    {"category": "General Knowledge", "type": "boolean", "difficulty": "easy",
     "question": "Nutella is produced by the German company Ferrero.", "correct_answer": "False",
     "incorrect_answers": ["True"]},
    {"category": "Entertainment: Japanese Anime & Manga", "type": "boolean", "difficulty": "easy",
     "question": "In Kill La Kill, the weapon of the main protagonist is a katana. ", "correct_answer": "False",
     "incorrect_answers": ["True"]},
    {"category": "Entertainment: Video Games", "type": "multiple", "difficulty": "easy",
     "question": "What does IWHBYD stand for on the skull in the Halo series?",
     "correct_answer": "I Would Have Been Your Daddy",
     "incorrect_answers": ["I Wanna Have Babies You Down", "I Would Hate Being Your Driver",
                           "I Would Have Bought Your Dog"]},
    {"category": "Science & Nature", "type": "multiple", "difficulty": "easy",
     "question": "What does DNA stand for?",
     "correct_answer": "Deoxyribonucleic Acid",
     "incorrect_answers": ["Deoxyribogenetic Acid", "Deoxyribogenetic Atoms", "Detoxic Acid"]},
    {"category": "General Knowledge", "type": "multiple", "difficulty": "easy",
     "question": "What is on display in the Madame Tussaud&#039;s museum in London?",
     "correct_answer": "Wax sculptures",
     "incorrect_answers": ["Designer clothing", "Unreleased film reels", "Vintage cars"]},
    {"category": "Entertainment: Video Games", "type": "multiple", "difficulty": "easy",
     "question": "Which of these Starbound races has a Wild West culture?", "correct_answer": "Novakid",
     "incorrect_answers": ["Avian", "Human", "Hylotl"]},
    {"category": "Entertainment: Video Games", "type": "multiple", "difficulty": "easy",
     "question": "What year was the game &quot;Overwatch&quot; revealed?", "correct_answer": "2014",
     "incorrect_answers": ["2015", "2011", "2008"]},
    {"category": "Entertainment: Japanese Anime & Manga", "type": "multiple", "difficulty": "easy",
     "question": "What was Ash Ketchum&#039;s second Pokemon?", "correct_answer": "Caterpie",
     "incorrect_answers": ["Charmander", "Pikachu", "Pidgey"]},
    {"category": "Entertainment: Video Games", "type": "multiple", "difficulty": "easy",
     "question": "Which of these characters is the mascot of the video game company SEGA?",
     "correct_answer": "Sonic the Hedgehog", "incorrect_answers": ["Dynamite Headdy", "Alex Kidd", "Opa-Opa"]},
    {"category": "Entertainment: Music", "type": "multiple", "difficulty": "easy",
     "question": "What was Rage Against the Machine&#039;s debut album?",
     "correct_answer": "Rage Against the Machine",
     "incorrect_answers": ["Evil Empire", "Bombtrack", "The Battle Of Los Angeles"]},
    {"category": "General Knowledge", "type": "multiple", "difficulty": "easy",
     "question": "Five dollars is worth how many nickles?", "correct_answer": "100",
     "incorrect_answers": ["50", "25", "69"]},
    {"category": "Entertainment: Music", "type": "multiple", "difficulty": "easy",
     "question": "Which of these is the name of a song by Tears for Fears?", "correct_answer": "Shout",
     "incorrect_answers": ["Scream", "Yell", "Shriek"]},
    {"category": "Science & Nature", "type": "multiple", "difficulty": "easy",
     "question": "The element involved in making human blood red is which of the following?",
     "correct_answer": "Iron",
     "incorrect_answers": ["Copper", "Iridium", "Cobalt"]},
    {"category": "Entertainment: Video Games", "type": "multiple", "difficulty": "easy",
     "question": "What is the default alias that Princess Garnet goes by in Final Fantasy IX?",
     "correct_answer": "Dagger", "incorrect_answers": ["Dirk", "Garnet", "Quina"]},
    {"category": "Entertainment: Video Games", "type": "multiple", "difficulty": "easy",
     "question": "The starting pistol of the Terrorist team in a competitive match of Counter Strike: Global Offensive is what?",
     "correct_answer": "Glock-18", "incorrect_answers": ["Tec-9", "Desert Eagle", "Dual Berretas"]},
    {"category": "Entertainment: Music", "type": "boolean", "difficulty": "easy",
     "question": "The song &quot;Stronger Than You&quot; is a single by Estelle, who played Garnet in Steven Universe.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"category": "Science: Computers", "type": "multiple", "difficulty": "easy",
     "question": "Which computer language would you associate Django framework with?", "correct_answer": "Python",
     "incorrect_answers": ["C#", "C++", "Java"]},
    {"category": "Entertainment: Film", "type": "multiple", "difficulty": "easy",
     "question": "The 2002 film &quot;28 Days Later&quot; is mainly set in which European country?",
     "correct_answer": "United Kingdom", "incorrect_answers": ["France", "Italy", "Germany"]},
    {"category": "General Knowledge", "type": "boolean", "difficulty": "easy",
     "question": "Romanian belongs to the Romance language family, shared with French, Spanish, Portuguese and Italian. ",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"category": "Entertainment: Video Games", "type": "multiple", "difficulty": "easy",
     "question": "Which of the following is not a faction in Tom Clancy&#039;s The Division?",
     "correct_answer": "CDC",
     "incorrect_answers": ["Cleaners", "Last Man Batallion", "Rikers"]},
    {"category": "Entertainment: Japanese Anime & Manga", "type": "multiple", "difficulty": "easy",
     "question": "Who is the author of the manga series &quot;Astro Boy&quot;?", "correct_answer": "Osamu Tezuka",
     "incorrect_answers": ["Mitsuteri Yokoyama", "Takao Saito", "Yoshihiro Tatsumi"]},
    {"category": "Entertainment: Video Games", "type": "multiple", "difficulty": "easy",
     "question": "In Animal Crossing, who is the manager of the town shop?", "correct_answer": "Tom Nook",
     "incorrect_answers": ["Mr. Resetti", "Gracie", "K.K. Slider"]},
    {"category": "Entertainment: Film", "type": "boolean", "difficulty": "easy",
     "question": "Brandon Routh plays the titular character in the movie &quot;John Wick&quot;.",
     "correct_answer": "False", "incorrect_answers": ["True"]},
    {"category": "Entertainment: Japanese Anime & Manga", "type": "boolean", "difficulty": "easy",
     "question": "In Chobits, Hideki found Chii in his apartment.", "correct_answer": "False",
     "incorrect_answers": ["True"]}, {"category": "Science & Nature", "type": "multiple", "difficulty": "easy",
                                      "question": "What is the speed of light in a vacuum?",
                                      "correct_answer": "299,792,458 m\/s",
                                      "incorrect_answers": ["50,461 m\/s", "308,215,043 m\/s",
                                                            "751,665,014,151 m\/s"]},
    {"category": "Entertainment: Television", "type": "multiple", "difficulty": "easy",
     "question": "In &quot;Rick And Morty&quot;, who shot &quot;Mr. Poopybutthole&quot; in the episode &quot;Total Rickall&quot;?",
     "correct_answer": "Beth", "incorrect_answers": ["Rick", "Jerry", "Morty"]},
    {"category": "Science: Computers", "type": "multiple", "difficulty": "easy",
     "question": "How long is an IPv6 address?", "correct_answer": "128 bits",
     "incorrect_answers": ["32 bits", "64 bits", "128 bytes"]},
    {"category": "Science: Computers", "type": "multiple", "difficulty": "easy",
     "question": "In computing, what does LAN stand for?", "correct_answer": "Local Area Network",
     "incorrect_answers": ["Long Antenna Node", "Light Access Node", "Land Address Navigation"]},
    {"category": "Sports", "type": "multiple", "difficulty": "easy",
     "question": "When was the FC Schalke 04 founded?",
     "correct_answer": "1904", "incorrect_answers": ["1909", "2008", "1999"]},
    {"category": "Sports", "type": "multiple", "difficulty": "easy",
     "question": "The Los Angeles Dodgers were originally from what U.S. city?", "correct_answer": "Brooklyn",
     "incorrect_answers": ["Las Vegas", "Boston", "Seattle"]},
    {"category": "Entertainment: Video Games", "type": "multiple", "difficulty": "easy",
     "question": "What is the name of the talking cat in Persona 5?", "correct_answer": "Morgana",
     "incorrect_answers": ["Teddie", "Marie", "Ryuji"]},
    {"category": "Entertainment: Television", "type": "multiple", "difficulty": "easy",
     "question": "In the show &quot;Dragonball Z&quot;, what is the name of Cell&#039;s most powerful attack?",
     "correct_answer": "Solar Kamehameha",
     "incorrect_answers": ["Super Kamehameha", "Cell Kamehameha", "Android Kamehameha"]},
    {"category": "History", "type": "multiple", "difficulty": "easy",
     "question": "Who rode on horseback to warn the Minutemen that the British were coming during the U.S. Revolutionary War?",
     "correct_answer": "Paul Revere", "incorrect_answers": ["Thomas Paine", "Henry Longfellow", "Nathan Hale"]},
    {"category": "General Knowledge", "type": "multiple", "difficulty": "easy",
     "question": "What is the profession of Elon Musk&#039;s mom, Maye Musk?", "correct_answer": "Model",
     "incorrect_answers": ["Professor", "Biologist", "Musician"]},
    {"category": "Entertainment: Video Games", "type": "multiple", "difficulty": "easy",
     "question": "In the Video Game, Half-life, what type of US military force starts clearing out the Black Mesa Research Facility?",
     "correct_answer": "The HECU", "incorrect_answers": ["Navy Seals", "The Combine", "The Marines"]},
    {"category": "Entertainment: Video Games", "type": "multiple", "difficulty": "easy",
     "question": "What vehicle in PUBG has the highest top speed?", "correct_answer": "Motorcycle",
     "incorrect_answers": ["PG-117", "Dacia", "Buggy"]}
]
